---
output:
  html_document:
    css: style1.css
    theme: cosmo
    highlight: textmate
---

## Econometrics form {.tabset .tabset-pills}

### Univariate Model


$$y_i=\beta_0+\beta_1x_{1,i}+u_i$$
Under linear regression assumptions

$$\hat{\beta_o}=\overline{y}-\hat{\beta_1} \overline{x_{1}}$$
$$\hat{\beta_1}=\frac{\sum_{i=1}^{T} (x_{1,i}-\overline{x_{1}})(y_i-\overline{y})}{\sum_{i=1}^{T} (x_{1,i}-\overline{x_{1}})^2}=\frac{\sum_{i=1}^{T} (x_{1,i}-\overline{x_1})y_i}{\sum_{i=1}^{T} (x_{1,i}-\overline{x_1})^2}=\frac{\sum_{i=1}^{T} (y_i-\overline{y})x_{1,i}}{\sum_{i=1}^{T} (x_{1,i}-\overline{x_{1}})^2}$$

$$\hat{y_i}=\hat{\beta_0}+\hat{\beta_1}x_{1.i}$$
$$\hat{u_i}=y_i-\hat{y_i}$$

$$\mathbb{E} [\hat{\beta_0}]=\beta_0$$
$$\mathbb{E} [\hat{\beta_1}]=\beta_1$$

$$Var(\hat{\beta_0})=\frac{\sigma^2 \sum_{i=1}^T x_{1,i}^2}{T \cdot \sum_{i=1}^T (x_{1,i}-\overline{x_1})^2}=\frac{\sigma^2 \sum_{i=1}^T x_{1,i}^2}{T \cdot SST_1}$$
$$Var(\hat{\beta_1})=\frac{\sigma^2}{\sum_{i=1}^T (x_{1.i}-\overline{x_1})^2}=\frac{\sigma^2}{SST_1}$$

$$\hat{\sigma}^2=\frac{\sum_{i=1}^T \hat{u_i}^2 }{T-K-1}$$

### $R^2$

$$SST=SSE+SSR$$

$$\sum_{i=1}^{T} (y_i-\overline{y})^2 = \sum_{i=1}^{T} (\hat{y_i}-\overline{y})^2 + \sum_{i=1}^{T} (y_i-\hat{y_i})^2$$

$$R^2=\frac{\sum_{i=1}^{T} (\hat{y_i}-\overline{y})^2}{\sum_{i=1}^{T} (y_i-\overline{y})^2}=1-\frac{\sum_{i=1}^{T} (y_i-\hat{y_i})^2}{\sum_{i=1}^{T} (y_i-\overline{y})^2}$$

### Multivariate Model

$$y_i=\beta_0+\beta_1x_{1,i}+\beta_2x_{2,i}+...+\beta_kx_{k,i}+u_i$$

Under linear regression assumptions 

$$\mathbb{E} [\hat{\beta_j}]=\beta_j$$
$$Var(\hat{\beta_j})=\frac{\sigma^2}{SST_j(1-R_j^2)}=\frac{\sigma^2}{SST_j}\cdot VIF_j$$


| Models 	| Regression 	| $\beta_1$ 	| $Slope=\frac{\partial y}{\partial x}$ 	| Interpretation 	|
|:---:	|:---:	|:---:	|:---:	|:---:	|
| Level-Level 	| $y_i=\beta_0+\beta_1x_i+u_i$ 	| $\frac{\Delta y_i}{\Delta x_i}$ 	| $\beta_1$ 	| Level changes 	|
| Level-Log 	| $y_i=\beta_0+\beta_1 ln(x_i)+u_i$ 	| $\frac{\Delta y_i}{\Delta \%x_i}$ 	| $\beta_1 \frac{1}{x}$ 	| Semi-Elasticity 	|
| Log-Level 	| $ln(y_i)=\beta_0+\beta_1x_i+u_i$ 	| $\frac{\Delta \%y_i}{\Delta x_i}$ 	| $\beta_1 y$ 	| Semi-Elasticity 	|
| Log-Log 	| $ln(y_i)=\beta_0+\beta_1 ln(x_i)+u_i$ 	| $\frac{\Delta \%y_i}{\Delta \%x_i}$ 	| $\beta_1 \frac{y}{x}$ 	| Elasticity 	|


### Bias

$$y_i=\beta_0+\beta_1x_{1,i}+\beta_1x_{2,i}+u_i \Rightarrow Real$$
$$y_i=\gamma_0+\gamma_1x_{1,i}+u_i \Rightarrow Estimate$$


$$\mathbb{E}[\hat{\gamma_1}]=\beta_1+\underbrace{\beta_2 \frac{Cov(X_1,X_2)}{Var(X_1)}}_{\text Bias}$$

|  	| $Cov(X_1,X_2)>0$ 	| $Cov(X_1,X_2)<0$ 	|
|:---:	|:---:	|:---:	|
| $\beta_2>0$ 	| Overestimated 	| Underestimated 	|
| $\beta_2<0$ 	| Underestimated 	| Overestimated 	|



### Inference

$$t_{\hat{\beta_j}}= \frac{\hat{\beta_j}-\beta_j}{sd(\hat{\beta_j})} \sim t_{(T-K-1)}$$

$$Pr\left[ \hat{\beta_j}-c_{\alpha} \cdot sd(\hat{\beta_j}) \leq \beta_j \leq \hat{\beta_j}+c_{\alpha} \cdot sd(\hat{\beta_j})\right]=1-\alpha$$

$$P_{value}=Pr[|t_{obs}|\geq |t_{\hat{\beta_j}}|]$$

$$F_{obs}=\frac{(SSR_{r}-SSR_{ur})/q}{(SSR_{ur})/(T-K-1)}=\frac{(R_{ur}^2-R_{r}^2)/q}{(1-R_{ur}^2)/(T-K-1)} \sim F_{q, t-k-1}$$

### Causal Effects

Rubin's Model
$$\underbrace{E[Y_i/W_i=1]-E[Y_i/W_i=0]}_{Observable \hspace{1mm} Mean \hspace{1mm} Difference} =\underbrace{E[Y_{1,i}/W_i=1]-E[Y_{0,i}/W_i=1]}_{ATT}+\underbrace{E[Y_{0,i}/W_i=1]-E[Y_{0,i}/W_i=0]}_{Selection \hspace{1mm} Bias}$$
$$ATE=E[Y_1-Y_0]$$
$$ATT=E[Y_1-Y_0/W_i=1]$$
$$ITT=E[Y_i/Z_i=1]-E[Y_i/Z_i=0]=ATT \cdot Pr[W_i=1/Z_i=1]$$

Assumptions

$$SUTVA \Rightarrow (Y_{0,i},Y_{1,i}) \hspace{2mm} \bot  \hspace{2mm} W_j \hspace{4mm} \forall j\neq i$$

$$Unconfoundedness \Rightarrow (Y_{0,i}, Y_{1,i}) \hspace{2mm}\bot \hspace{2mm} W_i/X_i$$

$$Overlap \Rightarrow 0<Pr[W_i=1/X_i]<1$$

Propensity Score

$$Regression \Rightarrow y_i=\tau w_i+\phi \underbrace{\hat{p(x_i)}}_{probit/logit} +e_i$$

$$Weighting \Rightarrow E[Y_{1,i}-Y_{0,i}]=E\left[\frac{(W_i-p(X_i))Y_i}{p(X_i)(1-p(X_i))}\right]$$

$$Matching \Rightarrow ATT^M=\frac{1}{N_T}\sum_{i:w_i=1} \left(y_{1,i}-\sum_{j:w_j=0} \overbrace{\phi(i,j)}^{Weights}y_{0,j} \right)$$

Differences in Differences
$$DiD=\underbrace{(Y_t^T-Y_t^C)}_{Post \hspace{1mm} Treatment \hspace{1mm} Differences} - \underbrace{(Y_{t-1}^T-Y_{t-1}^C)}_{Pre \hspace{1mm} Treatment \hspace{1mm} Differences}=\underbrace{(Y_t^T-Y_{t-1}^T)}_{Treaty \hspace{1mm} Differences} - \underbrace{(Y_t^C-Y_{t-1}^C)}_{Non \hspace{1mm} Treaty \hspace{1mm} Differences}$$

Synthetic Control
$$\hat{\alpha_{1,t}}=\underbrace{Y_{1,t}}_{Observed \hspace{1mm} Serie} - \underbrace{\sum_{j=2}^{J+1} \overbrace{w_j^*}^{Weights} Y_{j,t}}_{Synthetic \hspace{1mm} Serie} $$


### Time Series

AR(P) Models
$$E[y_t]=\frac{\phi_0}{(1-\sum_{i=1}^{p}\phi_i)}$$
$$Var[y_t]=\sigma_\varepsilon^2+\sum_{i=1}^{p}\phi_i\gamma_i$$
$$Cov[y_t,y_{t-1}]=\sum_{i=1}^{P}\phi_i\gamma_{j-i} \hspace{3mm} \forall j\geq 1$$
$$Corr[y_t,y_{t-s}]=\phi_1^s$$

MA(q) Models
$$E[y_t]=\theta_0$$
$$Var[y_t]=\left(1+\sum_{i=1}^{q} \theta_i^2\right) \sigma_\varepsilon^2$$
$$Cov[y_t,y_{t-s}]=\begin{cases}
    \sigma_\varepsilon^2 \sum_{j=0}^{q-s} \theta_j \theta_{j+s} & \text{si } s\leq q \hspace{3mm} where \hspace{2mm} \theta_0=1\\
    0 & \text{si } s> q \\
  \end{cases}$$

$$Corr[y_t,y_{t-s}]=\begin{cases}
\frac{\sum_{j=0}^{q-s} \theta_j \theta_{j+s}}{(1+\sum_{i=1}^{q} \theta_i^2)} & \text{si } s\leq q \hspace{3mm} where \hspace{2mm} \theta_0=1\\
    0 & \text{si } s> q \\
  \end{cases}$$

¿White Noise?
$$Box-Pierce \Rightarrow T \sum_{j=1}^{k}\hat{\rho_j}^2 \sim \chi_{(k-p-q)}$$

$$Ljung-Box \Rightarrow T(T+2) \sum_{j=1}^{k}\frac{\hat{\rho_j}^2}{(T-k)} \sim \chi_{(k-p-q)}$$

¿Structural Break?

$$Chow \Rightarrow F=\frac{(SSR-SSR_1-SSR_2)/n}{(SSR_1+SSR_2)(T-2n)}\sim F_{n,(T-2n)}$$
¿Unit Root?
$$Dickey-Fuller \Rightarrow \Delta y_t=\mu+\beta t+\gamma y_{t-1}+u_t$$
$$Dickey-Fuller \hspace{1mm} extended \Rightarrow \Delta y_t=\mu+\beta t+\gamma y_{t-1}+\rho_1\Delta y_{t-1}+\rho_2\Delta y_{t-2}+...+\rho_p\Delta y_{t-p}+u_t$$











